version: '3.8'

services: 
  web:
    build:
      context: ./
    ports:
      - 8000:8000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_IP=${DB_IP}
  
